version: "3.7"

services:
  app:
    image: node:alpine
    restart: unless-stopped
    working_dir: /app/
    volumes:
      - ./:/app/
    environment:
      NODE_ENV: production
    ports:
      - "8080:8080"
      - "9090:9090"
    networks:
      - back
    command: npm start

networks:
  back:
# volumes:
#   db_data:
